name: "Branch & PR"

on: [ push ]

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - name: Test
      run: make test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - name: Lint
      run: make lint
  build:
    name: Build Code
    runs-on: ubuntu-latest
    needs: [test,lint]
    permissions:
      security-events: write
    strategy:
      fail-fast: true
      matrix:
        language: [ 'go' ]
    steps:
    - name: Checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - name: Init CodeQL
      uses: github/codeql-action/init@27ea8f8fe5977c00f5b37e076ab846c5bd783b96
      with:
        languages: ${{ matrix.language }}
    - name: Build
      run: make build
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@27ea8f8fe5977c00f5b37e076ab846c5bd783b96
  package:
    name: Package
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@11ba7d3f32dc7cc919d1c43f1fec1c05260c26b5
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: mattermost/poc-simple-service-pipelines
          event-type: package-application
          client-payload: '{"github": ${{ toJson(github) }}}'    
