name: "Private"

on: 
  workflow_dispatch:
    inputs:
      job:
        description: 'Job Name'
        required: false 
        type: string
      status:
        description: 'Job status'
        type: string
        required: false 
      output:
        description: 'Output'
        type: string
        required: false 
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - name: Build
      if: ${{ inputs.job == 'Build' }}
      run: |
        echo -e "${{ inputs.output }}"
        if [[ ${{ inputs.status }} != "success" ]]; then
          exit 1
        fi
      
  